name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no quickpuff795@34.44.225.81 << 'EOF'
            # Navigate to your project directory
            cd /home/quickpuff795/quick-puff-node

            # Pull the latest code
            git pull origin main
            
            # Install dependencies
            npm install

            # Start or restart the app using PM2
            pm2 start server.js --name "server" || pm2 restart "server"

            # Save the PM2 process list
            pm2 save
          EOF
