name: CI/CD to Google Cloud VM

on:
  push:
    branches:
      - main # Adjust this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH Agent and Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GC VM
        env:
          HOST: 34.44.225.81
          USERNAME: quickpuff795
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} << 'EOF'
            # Navigate to your project directory
            cd /home/quickpuff795/quick-puff-node

            # Run deployment commands
            git checkout main
            git pull origin main
            npm install

            # Start the app with a specific name (pm2 will handle it correctly now)
            pm2 start server.js --name "server" || pm2 restart "server"

            pm2 save  # Save the pm2 process list
            exit
          EOF

      - name: Deploy to AWS EC2
        env:
          HOST_VM2: 13.127.53.137
          USERNAME_VM2: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.USERNAME_VM2 }}@${{ env.HOST_VM2 }} << 'EOF'
            # Navigate to your project directory
            cd /home/ubuntu/quick-puff-node

            # Run deployment commands
            git pull origin main
            npm install

            # Start the app with a specific name (pm2 will handle it correctly now)
            pm2 start server.js --name "server" || pm2 restart "server"

            pm2 save  # Save the pm2 process list
            exit
          EOF
