name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy-to-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH Agent and Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GC VM Production
        env:
          HOST: 34.44.225.81
          USERNAME: quickpuff795
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} << 'EOF'
            # Navigate to your project directory
            cd /home/quickpuff795/quick-puff-node

            # Run deployment commands
            git checkout main
            git pull origin main
            npm install

            # Start the app with a specific name
            pm2 start server.js --name "server-prod" || pm2 restart "server-prod"

            pm2 save  # Save the pm2 process list
            exit
          EOF

  deploy-to-development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH Agent and Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to AWS EC2 Development
        env:
          HOST_VM2: 65.0.104.81
          USERNAME_VM2: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.USERNAME_VM2 }}@${{ env.HOST_VM2 }} << 'EOF'
            # Navigate to your project directory
            cd /home/ubuntu/quick-puff-node

            # Run deployment commands
            git checkout development
            git pull origin development
            npm install

            # Start the app with a specific name
            pm2 start server.js --name "server-dev" || pm2 restart "server-dev"

            pm2 save  # Save the pm2 process list
            exit
          EOF
